### ISSUE TITLE
s3 권한 요청

### ISSUE THREAD

**Issue by shinwonse** [sullog-official/sullog-server#104]
https://sullog-s3.s3.ap-northeast-2.amazonaws.com/%E1%84%89%E1%85%B3%E1%84%8F%E1%85%B3%E1%84%85%E1%85%B5%E1%86%AB%E1%84%89%E1%85%A3%E1%86%BA%202023-01-27%20%E1%84%8B%E1%85%A9%E1%84%92%E1%85%AE%207.50.10.png

와 같은 경험 이미지 요청이 403에러를 반환합니다. 

- localhost:3000
- https://sullog-client.vercel.app

에 대한 권한 요청 부탁드립니다

**Comment by seungyeonchoi** [comment]
https://minholee93.tistory.com/entry/AWS-HTTP-Referer%EB%A1%9C-S3-%EC%A0%91%EA%B7%BC-%EC%A0%9C%ED%95%9C%ED%95%98%EA%B8%B0 참고해서 referer 기반 권한 설정
