### ISSUE TITLE
/records/me 위도, 경도 0,0으로 오는 이슈

### ISSUE THREAD

**Issue by syoung125** [sullog-official/sullog-server#113]
<img width="543" alt="image" src="https://github.com/sullog-official/sullog-server/assets/39763891/5f771509-3fe5-4a57-968b-a7a8bede927b">

**Comment by seungyeonchoi** [comment]
테스트 데이터는 0,0으로 설정되어있는거 같네요!?!

**Comment by cnpcnp99** [comment]
네 승연님 말씀이 맞네요. 현재 조회하셨던 기록 데이터에 매핑된 alcohol_id를 2로 변경해봤는데 한 번 다시 조회해보시겠어요? @syoung125

**Comment by cnpcnp99** [comment]
서영님 확인 완료

![image](https://github.com/sullog-official/sullog-server/assets/47394504/083745d2-92b0-4992-b0b3-82c640d3fc03)
