### ISSUE TITLE
카카오 로그인 관련 이슈

### ISSUE THREAD

**Issue by shinwonse** [sullog-official/sullog-server#127]
안녕하세요. 카카오 로그인 관련 이슈가 있어 이슈 남깁니다.

현재 프론트엔드팀에서는 로컬 개발 환경 이외에 두 가지 스테이지에서 배포하여 테스트를 진행중인데요, 다음과 같은 도메인을 갖습니다.
- https://sullog-dev.vercel.app/login (preview stage)
- https://sullog-client.vercel.app/ (prod stage)

현재 위 두 도메인의 카카오 redirect url인 https://sullog**/login이 허용되지 않은 것으로 보입니다. 확인 한번 부탁드릴게요~

**Comment by seungyeonchoi** [comment]
클라이언트와 서버의 개발환경을 정리해보면 이와 같은데요!
```
- 클라이언트 환경: local, beta, production
- 서버 환경: local, alpha, live
- 매핑시키면?
    - 클: local → 서: alpha
    - 클: beta -> 서: stage 서버를 운영하지 않음.
    - 클: production → 서: live
```
(클라이언트 분류는 과거 메신저 기준으로 작성했습니다: https://github.com/sullog-official/sullog-server/issues/76)

redirect uri는 이렇게 등록되어 있는 상황입니다
```
http://localhost:3000/login
https://sullog-client.vercel.app/login
```

 stage 서버를 운영하지 않기 때문에,
preview stage -> alpha 서버, prod stage -> real 서버 
위와 같이 redirect uri 를 설정해주실 수 있나요!?

**Comment by shinwonse** [comment]
```
http://localhost:3000/login
https://sullog-dev.vercel.app/login (추가)
https://sullog-client.vercel.app/login
```
이렇게도 가능하실까요?

**Comment by seungyeonchoi** [comment]
현재 서버구조에서 그렇게 하려면 서버 한대를 더 운영해야합니다
-> 서버 코드에서 미리 협의된 redirect uri값을 환경별로 관리하고 있고, 카카오 oauth 서버와 통신할 때 이용하고 있습니다. 따라서 환경에 따라 어떤 redirect uri가 쓰일지는 유동적으로 변하는게 아니라, 고정된 값이여서, `https://sullog-dev.vercel.app/login` 값으로 처리될 환경을 하나 더 만들어야합니당 

로직을 수정하는 방법으로는 redirect uri를 api 요청시 전달받을 수도 있겠는데, 적절한 방법일지는 확인이 필요할 것 같네요

**Comment by shinwonse** [comment]
아아 음 그렇다면 preview 배포를 빼는 쪽으로 가겠습니다. 서버 쪽 인프라를 고려하지 못했네요
