### ISSUE TITLE
sullog 자체적인 jwt 토큰 발급 과정이 필요할까요?!

### ISSUE THREAD

**Issue by seungyeonchoi** [sullog-official/sullog-server#2]
카카오 서버에서 전달받은 access token과 refresh token을 저장하고, 이 값으로 인증을 처리하면 되지 않을까.. 하는 생각이 들었습니다
- spring security 알못- 

관련 작업: #1

**Comment by shinwonse** [comment]
jwt 없이 클라이언트로 인증 정보를 전달할 수 있나요?

**Comment by seungyeonchoi** [comment]
client id/ client secret 이 비밀이니까 괜찮지 않을까 ...싶었는데 아무래도 안되겠져 ..

**Comment by cnpcnp99** [comment]
카카오에서 발급해주는 access, refresh 토큰은 직접 expire 기간을 설정할 수 있나요?

**Comment by seungyeonchoi** [comment]
문서확인해봤을 때는 그런 기능은 없는 것 같습니다 !!

근데 이 이슈 논의할 필요 없습니다!!

처음에는 oauth + jwt + spring security 를 직접 핸들링하는게 중요도 대비 어려운과정같아서 단순하게 가보고 싶었는데, 나름대로 `org.springframework.boot:spring-boot-starter-oauth2-client` 를 터득해서 이슈없을 것 같씁니다
