### ISSUE TITLE
키워드 기반 검색 api에서 최근검색어 업데이트를 코드에 어떻게 녹일까?

### ISSUE THREAD

**Issue by seungyeonchoi** [sullog-official/sullog-server#41]
### 적용 대상 api
1. api/alcohols/search
2. records/search (#34)

### 현황
1번 API는 `alcoholService.getAlcoholInfo` 비즈니스 로직에서 같이 수행중
2번 API는 해당 기능 누락됨

### 개발방향
1. 1번 API 처럼 비즈니스 로직에 녹이기
2. AOP 로 분리
  - 의견이 든 배경: 키워드 기반 검색에서 최근 검색어 업데이트가 주요 비즈니스 로직이 아닌 것 같아서..!

**Comment by cnpcnp99** [comment]
저도 공감하는 바입니다. 다만 최근 검색어를 업데이트하는 로직 또한 꽤 비중이 있는 로직이라고 생각하는데 AOP로 분리할 경우 그 비중이 명시적으로 드러나지 않을 가능성이 있지 않을까 조심스럽게 생각해봅니다...🤔

분명 지금과 비슷한 케이스의 로직이 왕왕 발생할텐데 이럴 때 보통 어떻게 핸들링하시나요? 일단 저는 1번 케이스와 같이 그냥 넣는 편이긴 합니다. 하지만 늘 아쉽다고 느끼고는 있죠ㅎ

**Comment by seungyeonchoi** [comment]
맞씁니다.. AOP로 분리하게 될 경우, 이 로직이 호출되는지 알 수 없게 된다는 큰 문제가 있는 것 같습니다 !!
코멘트 적으면서 생각해봤는데, 저도 <최근 검색어 업데이트> 로직의 비중에 더 공감하여서 AOP보다는 분명하게 비즈니스 로직에 녹이는게 좋을 것 같습니다!! 

흠... 저도 AOP로 처리한 경험은 없고 다 1번처럼 작성했습니다!! 애매하다는 것은 모든 방안이 장/단이 있다는 것이니,  항상 다른 팀원들과 논의해서 결정된 방향으로 따르고 있습니다!!

**Comment by cnpcnp99** [comment]
넵넵 좋은 것 같습니다. AOP로 따로 빼는 경우는 모든 로직에 자주 등장하면서도 그 중요도가 낮을 때 적용하는게 맞는 것 같다는게 개인적인 생각입니다!

**Comment by seungyeonchoi** [comment]
방향성이 정해져서 클로즈합니다!
