### ISSUE TITLE
제가 작성한 코드에서 mapper 인터페이스가 승연님이 말씀하신 repository와 같은 개념일까요?

### ISSUE THREAD

**Issue by cnpcnp99** [sullog-official/sullog-server#5]
제가 샘플로 mybatis를 사용하는 코드를 작성했는데 이때 MemberMapper 인터페이스에 @Mapper 어노테이션을 달았고,  xml에서는 해당 인터페이스를 참조하도록 설정을 해주었습니다. 이렇게 되면 이 인터페이스를 개념적으로 repository라고 하는 건가요? 아니면 mappe를 한 번 더 추상화한게 repository일까요? JPA에서는 그냥 repository로 사용하고 mapper는 쓸 일이 없다보니 신경쓰지 않았던 부분인데 mybatis를 쓰게 되면서 개념적으로 조금 헷갈리는 것 같아 질문드립니다.

- 참고 -  #4

**Comment by seungyeonchoi** [comment]
저는 `이렇게 되면 이 인터페이스를 개념적으로 repository라고 하는 건가요? ` 라고 생각하였습니다!! 질문보고 애매한 부분인 것 같아서 찾아봤는데, 잘 정리해둔 글이 있어서 같이 남겨둡니당
->  https://pamyferret.tistory.com/69

**Comment by cnpcnp99** [comment]
오 감사합니다. 남겨주신 레퍼런스 읽고 가장 중요하게 생각한 부분은 빈 등록을 어떤 방식으로 할 거냐의 차이인 것 같네요 개념적으로 명확하게 알고 사용하면 뭘 사용하건 큰 문제는 없을 것으로 보입니다.
