### ISSUE TITLE
제공받은 전통주, 브랜드 정보 파싱해서 DB에 저장하기

### ISSUE THREAD

**Issue by cnpcnp99** [sullog-official/sullog-server#52]
https://github.com/Jinho1011/naver-term-crawler/blob/master/data/%EC%A0%84%ED%86%B5%EC%A3%BC.json

해당 데이터를 파싱해서 DB에 전통주 정보 저장하기

**Comment by seungyeonchoi** [comment]
@cnpcnp99 의재님 데이터 이슈있는 90개 관련해서 간단히 히스토리 작성 부탁드립니다!\
-> 용량은 데이터 구조에 포함되지 않았서 skip했음. 파싱 대상에서 아예 제외 예정
