### ISSUE TITLE
회원가입 시 search_word_list 가 null로 insert되는 이슈

### ISSUE THREAD

**Issue by cnpcnp99** [sullog-official/sullog-server#66]
4/3 오늘 프론트 측에서 카카오 로그인 작업하던 중에 발견한 버그입니다.
일단 임시로 mysql에 default value로 "[]"로 넣으려 했으나 LONGTEXT이다보니 따로 값을 넣어줄 수가 없네요.
확인 가능하시면 한 번만 해당 이슈 체크 부탁드리겠습니다.

**Comment by seungyeonchoi** [comment]
![image](https://user-images.githubusercontent.com/48347010/229534504-726b0aaf-9245-4e74-b0e5-2ecb1e47b65e.png)

혹시 not null 제약조건이있나용 ..?

**Comment by cnpcnp99** [comment]
아뇨 없습니다 그래서 그냥 Null로 insert 되는 거 같아요

**Comment by seungyeonchoi** [comment]
null이 들어가고 -> null 을 조회해서 처리하지 못한다? 가 이슈인가용?!?!
null 이 들어가는게 이슈인가용!?

**Comment by cnpcnp99** [comment]
null이 들어가는게 이슈라고 생각합니다. 처음 가입할 때 "[]"가 기본적으로 들어가야되는 걸로 알고 있습니다!

**Comment by seungyeonchoi** [comment]
앗 그렇게 정했었나여!?!?!??! ㅎㅁㅎ!!! 
[]을 넣을 것 이었다면, not null 제약조건을 줬을 것같은데 . .

**Comment by cnpcnp99** [comment]
앗 그런가요...! not null, null의 경우 딥하게 얘기된 부분이 없었어서 그럴 수 있을 것 같습니다.
대신 search_word_list의 경우 TypeHandler를 쓰다보니 []가 디폴트로 들어가야되지 않나?라고 생각했었습니다.

**Comment by seungyeonchoi** [comment]
아하 거기서부터는 정하기 나름인 것 같습니다 ! 최근검색어 cud 하면서 null을 핸들링할지 / 말지에 대한 부분인 것 같은데 저는 디폴트로 값을 넣어준다면 not null 제약조건도 같이 줘야할 것 같아요 !! 

근데 또 궁금한건 저게 null로 insert되면서, 저 null을 조회해오고 -> 응답값을 생성하는 과정에서 예외가 발생한건가용!? 어떤 경로로 무슨 문제(null로 insert된 결과가 파생한)가 발견되었나요!? (디폴트로 []를 넣어서 해결하려는 상황이 무엇인지가 궁금합니닷 !!)

**Comment by cnpcnp99** [comment]
에러 정황은 
1. 프론트 측에서 카카오 로그인 진행할 때 400에러가 난다고 해 확인하던 중 
2. 지금 버전으로 배포하기 전에 어찌어찌 회원가입되어있던 계정이 db에 있어서 해당 계정을 지워 다시 가입을 하도록 했고
3. 무사히 가입은 성공했으나 search_word_list 컬럼에 null값이 들어가
4. select member를 할 때 mybatis resultMap을 통해 매핑될 때 null이 있어 result set에 매핑을 하지 못해 에러가 나는 상황이었습니다.

A. 1번의 400에러 로그
`400 Bad Request: "{"error":"invalid_grant","error_description":"authorization code not found for code=o39D3YKEc4BuAH9_E8Oi_qVq8oqt9F06YJOwQrjuIC2DzYzXOOPVPFXZER3LH9cGAPDq2gopyNkAAAGHR11F7g","error_code":"KOE320"}"`

B. 4번에서의 해당 에러 로그
`Caused by: org.apache.ibatis.executor.result.ResultMapException: Error attempting to get column 'search_word_list' from result set.  Cause: java.lang.IllegalArgumentException: argument "content" is null`

**Comment by cnpcnp99** [comment]
A의 경우 프론트 측에서 헤더에 리스폰스가 있다는 것을 모르고 아무 리턴도 없다고 생각해 반복적으로 다시 요청하는 과정에서 얻은 에러같습니다. 같은 code값을 여러번 넘겨 생겼을 확률이 높겠네요

- KOE320 에러 케이스
<img width="771" alt="image" src="https://user-images.githubusercontent.com/47394504/229542593-7327a953-7519-476a-bf55-84f97308fb93.png">

**Comment by seungyeonchoi** [comment]
아하아하 B는 결국 `null이 들어가고 -> null 을 조회해서 처리하지 못한다?` 의 문제군요!
설명감사합니다 !!

그럼 수정방향이 이렇게 정리될텐데, 
1) nullable한 케이스를 만들지 않는다 -> []를 디폴트로 넣는다
2) typehandler에서 null을 처리한다 

저는 둘다 괜찮을 것 같아서, 처음 제안주신 1안으로 수정하겠씁니다 !

**Comment by cnpcnp99** [comment]
넵 좋습니다!
