### ISSUE TITLE
배포시 수정되는 api-doc 커밋 관련

### ISSUE THREAD

**Issue by cnpcnp99** [sullog-official/sullog-server#70]
배포 시 api-doc에 버전 정보 등 수정사항이 생길 경우 이와 관련해 dev 브랜치에서 바로 커밋을 하는게 나을지 이 역시도 브랜치를 파서 PR을 올리는 형식이 나을지 고민됩니다 의견 주시면 감사하겠습니다.

**Comment by seungyeonchoi** [comment]
별도 pr + 셀프 머지 가능
정책으로 가는건 어떨까용!? 

아래와 같이 생각합니다!
- 별도 pr로 올리기: 히스토리 관리에 용이 (<배포>라는 라벨을 만들어서 붙여두면 나중에 트래킹하기 쉬울 것 같습니다!)
- 셀프 머지 가능: 수정사항에 대한 리뷰가 꼭 필요한 것이 아니니까 ..!

**Comment by cnpcnp99** [comment]
넵넵 좋은 생각인 것 같습니다 다음 배포부터 이렇게 작업하겠습니다~
