### ISSUE TITLE
깃허브 마일스톤 기능 활용하기

### ISSUE THREAD

**Issue by seungyeonchoi** [sullog-official/sullog-server#72]
배포할 때 마다 배포 히스토리를 작성하고 있는데, 작업한 내용이 점점 누적되면서 히스토리 작성 또한 번거로워 지는 것 같습니다!

마일스톤 기능을 통해 한 버전에 배포되는 pr은 하나의 마일스톤에 묶이도록 설정해두는건 어떨까요!?

EX. 지금까지 배포된 버전: v3, 다음 배포 버전: v4 상황
마일스톤에서 v4를 만들어두고, v3 배포 이후 ~ v4 배포 전까지 작업한 pr에는 v4 마일스톤 설정
<img width="150" alt="image" src="https://user-images.githubusercontent.com/48347010/231188409-036333b2-8bb8-4252-bac9-a4309edca44e.png">
#71 에 예시로 추가해두었습니다!

추후 어떤 버전에 어떤 작업이 진행되었는지 알 수 있고, 배포 히스토리 작성에도 용이할 것 같습니다!

**Comment by cnpcnp99** [comment]
오 마일스톤 기능을 이렇게 써볼 생각은 못해봤네요 정말 좋은 것 같습니다! 이대로 진행하시죠

**Comment by seungyeonchoi** [comment]
2023-04-12 회의에서 api 버전관리에 마일스톤 활용하기로 결정
