### ISSUE TITLE
AWS S3 인프라 셋팅

### ISSUE THREAD

**Issue by seungyeonchoi** [sullog-official/sullog-server#8]
이미지 업로드용 S3 인프라 셋팅 부탁드립니다!!

**Comment by seungyeonchoi** [comment]
@cnpcnp99 님 혹씨 이거 먼저부탁드려도 될까요?! 오늘 어렵다면 일단 api에선 제외하겠습니다!

**Comment by cnpcnp99** [comment]
설정 후 계정 정보 전달드려서 승연님이 작업 진행 #20
