### ISSUE TITLE
AWS 마이그레이션에 따른 새 S3 인스턴스 접속 테스트 요청

### ISSUE THREAD

**Issue by cnpcnp99** [sullog-official/sullog-server#81]
아래 작업에 따라서 S3 정상 작동하는지 테스트한 번만 부탁드리겠습니다
#80

**Comment by seungyeonchoi** [comment]
경험 저장 api 테스트하면서, 첨부파일 하나 추가했는데 정상 업로드 및 접근 확인했습니다!

작업 감사합니다 !!!
