### ISSUE TITLE
/kakao api 호출시 400에러가 발생

### ISSUE THREAD

**Issue by syoung125** [sullog-official/sullog-server#83]
<img width="1339" alt="image" src="https://user-images.githubusercontent.com/39763891/232307850-4245e9bc-77f2-4ac5-a407-66440925e915.png">

**Comment by cnpcnp99** [comment]
## 문제 원인
- 사용자 테이블의 최근 검색어 column이 최초 가입 시 null로 insert되어서 생긴 오류.
- 이후 select 과정에서 ResultMap에 제대로 binding되지 않아서 해당 오류가 출력됨.

## 해결
- DB에 해당 컬럼에 직접 '[]' 값을 넣어주어 NPE을 방지함

## 기타
- 해당 오류의 경우 default로 '[]'가 insert되도록 API v4에서 이미 수정되어있음 - #71 
- 다만 해당 오류가 난 계정은 v3 당시에 가입된 계정이라 null로 insert된 상황
