### ISSUE TITLE
사용자 정보 가져오는 기능

### ISSUE THREAD

**Issue by shinwonse** [sullog-official/sullog-server#85]
사용자 정보를 가져오는 기능이 필요합니다
<img width="436" alt="image" src="https://user-images.githubusercontent.com/62709718/232494866-5b479cb0-7b09-4634-bf86-abfbd27be779.png">
해당 화면엣에서 사용자의 이름이 필요한데, 현재 api 문서에는 이 정보를 가져오는 기능이 없는 것 같습니다. 경험 통계 api 리턴값으로 사용자 이름 넣어줘도 될 것 같습니다

**Comment by cnpcnp99** [comment]
수정 완료
