### ISSUE TITLE
알코올 조회 api '주종' 항목 누락

### ISSUE THREAD

**Issue by syoung125** [sullog-official/sullog-server#86]
<img width="317" alt="image" src="https://user-images.githubusercontent.com/39763891/233817972-994c3d5c-885a-4f1b-880d-75561617b4d5.png">

- [관련 api 문서](http://ec2-13-124-179-45.ap-northeast-2.compute.amazonaws.com:8081/docs/api-doc.html#_%EC%A0%84%ED%86%B5%EC%A3%BC_id%EA%B8%B0%EB%B0%98_%EC%A0%84%ED%86%B5%EC%A3%BC_%EB%8B%A8%EA%B1%B4_%EC%A1%B0%ED%9A%8C)

**Comment by cnpcnp99** [comment]
컬럼 추가 작업 완료 + 정확한 주종 값은 추후 수정 예정입니다.
일단은 모든 주종값은 '기타'로 통일되어있는 점 참고 부탁드립니다.
@syoung125
