### ISSUE TITLE
전통주 경험 저장 시 Record title 필드가 필요한지 검토

### ISSUE THREAD

**Issue by syoung125** [sullog-official/sullog-server#87]
<img width="230" alt="image" src="https://user-images.githubusercontent.com/39763891/233834115-6cefcb47-c8b6-4d76-979c-e2258fa6c77b.png">

술이름은 알코올의 이름이라서 title을 사용하는 곳이 없는 것 같습니다!

**Comment by cnpcnp99** [comment]
흠 그렇군요 약간 경험글을 적을 때 당연히 제목도 있어야한다고 생각해서 title을 넣었던 거 같습니다.
경험에 별점 컬럼 누락된 이슈 작업하면서 title컬럼 삭제 작업도 같이 진행하겠습니다.
