### ISSUE TITLE
dto 를 어디까지 내려줄까?

### ISSUE THREAD

**Issue by seungyeonchoi** [sullog-official/sullog-server#9]
entity: DB에 저장된 데이터 모델

경험 저장 api를 구현하면서 고민에 빠진 부분입니다..

현재상황)
클라이언트에서 전달받은 dto에 이미지 리스트는 multipart타입이고, db에는 그 이미지가 저장된 경로를 저장하기로 한 상황.

case1) dto -> entity 변환을 컨트롤러에서 해야함!
컨트롤러에서 1) 이미지를 s3에 올려서 path 반환받음 2) 그걸로 dto -> entity 변환시 record객체에 넣어줌 3) record service에서 save함

뭔가..객체간 협력을 제대로 못쓰는 느낌 ?? 

case2) dto -> entity 변환을 서비스레이어에서 해야함!
dto를 service까지 내려주니까, 이미지 저장도 거기서 처리하고 반환받은 path를 바탕으로 record entity 생성가능!
-> 한마디로 record service에서 image upload service 이용

dto -> entity를 service에서 하는게 뭔가 이질적인 느낌이 듬 ... 

참고할만한글)
https://tecoble.techcourse.co.kr/post/2021-04-25-dto-layer-scope/

**Comment by seungyeonchoi** [comment]
애초에 multipartfile과 json dto는 같이 처리하려면, multipartfile타입을 그대로 쓸 수 없었음

**Comment by cnpcnp99** [comment]
회의 내용 바탕으로 진행

1. 되도록 controller에서 entity로 변환해 service단으로 넘겨줄 것
2. MultiPartFile의 경우 ImageService 클래스를 따로 만들어 핸들링 한 후 리턴 받은 imagePathList 문자열을 다시 RecordService로 넘겨주는 구조로 코드 구현
